apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-api-proxima-deployment
  labels:
    app: poll-api-proxima
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-api-proxima
  template:
    metadata:
      labels:
        app: poll-api-proxima
    spec:
      containers:
      - name: poll-api-proxima
        image: starcoin/starcoin_poll:sha-d9420ab
        ports:
        - containerPort: 8603
        env:
        - name: spring_profiles_active
          value: dev
        - name: STARCOIN_MYSQL_URL
          value: "jdbc:mysql://starcoin-db-2.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com:3306/poll_proxima?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
        - name: STARCOIN_MYSQL_USER
          value: "starcoin"
        - name: STARCOIN_MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-pwd
              key: password
        - name: STARCOIN_ES_URL
          value: "search-starcoin-es2-47avtmhexhbg7qtynzebcnnu64.ap-northeast-1.es.amazonaws.com"
        - name: STARCOIN_ES_PROTOCOL
          value: "https"
        - name: STARCOIN_ES_PORT
          value: "443"
        - name: STARCOIN_ES_USER
          value: elastic
        - name: STARCOIN_ES_PWD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-pw-elastic
              key: password
        - name: ALERT_MAIL_TO
          value: "jolestar@gmail.com,wk3368@163.com"
        - name: MAIL_SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: poll-alert-mail-secret
              key: smtphost
        - name: MAIL_SENDER_USERNAME
          valueFrom:
            secretKeyRef:
              name: poll-alert-mail-secret
              key: username
        - name: MAIL_SENDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: poll-alert-mail-secret
              key: password
        - name: FEISHU_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: feishu-webhook-secret
              key: url
        - name: POLL_API_PORT
          value: "8603"

