apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-api-halley-deployment
  labels:
    app: poll-api-halley
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-api-halley
  template:
    metadata:
      labels:
        app: poll-api-halley
    spec:
      containers:
      - name: poll-api-halley
        image: starcoin/starcoin_poll:sha-521dd8c
        ports:
        - containerPort: 8602
        env:
        - name: STARCOIN_MYSQL_URL
          value: "jdbc:mysql://starcoin-db-2.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com:3306/poll_halley?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
        - name: STARCOIN_MYSQL_USER
          value: "starcoin"
        - name: STARCOIN_MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-pwd
              key: password
        - name: STARCOIN_ES_URL
          value: "search-starcoin-es2-47avtmhexhbg7qtynzebcnnu64.ap-northeast-1.es.amazonaws.com"
        - name: STARCOIN_ES_PROTOCOL
          value: "https"
        - name: STARCOIN_ES_PORT
          value: "443"
        - name: STARCOIN_ES_USER
          value: elastic
        - name: STARCOIN_ES_PWD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-pw-elastic
              key: password
        - name: POLL_API_PORT
          value: "8602"
