apiVersion: v1
kind: Service
metadata:
  labels:
    app: poll-api
  name: poll-api
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8600
  selector:
    app: poll-api
  type: LoadBalancer
status:
  loadBalancer: {}