spring:
  mail:
    enable: true
    host: ${MAIL_SMTP_HOST}
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # auto: create # 开发阶段使用
          auto: update
  flyway:
    enabled: false # 启用或禁用 flyway

alert:
  mail:
    to: ${ALERT_MAIL_TO}
    subject-prefix: "Test: "

starcoin:
  network: main
#  json-rpc-url: https://barnard-seed.starcoin.org


logging:
  level:
    org:
      starcoin:
        poll:
          api:
            service: DEBUG

      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

      # 输出数据库模型（开发阶段）
      hibernate:
        tool:
          hbm2ddl: DEBUG

